In [55]:
import numpy as np

In [56]:
def dataset(rows=10,cols=5):
    return np.random.randint(1,101,size=(rows,cols))

In [57]:
def analyze_dataset(data):
    print(data)
    All_mean=np.mean(data)
    print("overAll_mean=",All_mean)
    print("Shape ::",data.shape)
    print("Dimensions ::",data.ndim)
    print("Variable_mean ::",np.mean(data,axis=0))
    print("Experiment_mean ::",np.mean(data,axis=1))
    print("maximum",np.max(data))
    print("minimum",np.min(data))
    print("above_mean",data[data>All_mean])
    reshaped = data.reshape(5, 10)
    print("reshaped data::\n",reshaped)
    flattened = reshaped.flatten()
    print("flattend::\n",flattened)
    

In [58]:
data=dataset()
analyze_dataset(data)

[[ 54  24  88  87   6]
 [ 67  86  45  40  64]
 [ 83  25  87  52  16]
 [ 90  93  58  69  56]
 [ 24  50  47  33  77]
 [ 29  14  92  80  95]
 [ 66  48  29  27 100]
 [ 84  35  70  49   8]
 [ 71  13  41  37   1]
 [ 63   4  88   9   8]]
overAll_mean= 51.64
Shape :: (10, 5)
Dimensions :: 2
Variable_mean :: [63.1 39.2 64.5 48.3 43.1]
Experiment_mean :: [51.8 60.4 52.6 73.2 46.2 62.  54.  49.2 32.6 34.4]
maximum 100
minimum 1
above_mean [ 54  88  87  67  86  64  83  87  52  90  93  58  69  56  77  92  80  95
  66 100  84  70  71  63  88]
reshaped data::
 [[ 54  24  88  87   6  67  86  45  40  64]
 [ 83  25  87  52  16  90  93  58  69  56]
 [ 24  50  47  33  77  29  14  92  80  95]
 [ 66  48  29  27 100  84  35  70  49   8]
 [ 71  13  41  37   1  63   4  88   9   8]]
flattend::
 [ 54  24  88  87   6  67  86  45  40  64  83  25  87  52  16  90  93  58
  69  56  24  50  47  33  77  29  14  92  80  95  66  48  29  27 100  84
  35  70  49   8  71  13  41  37   1  63   4  88   9   8]
