In [1]:
import numpy as np

In [2]:
experiment_A=np.array([12, 15, 14, 18, 20, 17, 16])
experiment_B=np.array([10, 13, 15, 16, 19, 21, 18])
print(experiment_A)
print(experiment_B)

[12 15 14 18 20 17 16]
[10 13 15 16 19 21 18]


In [3]:
mean_A=np.mean(experiment_A)
print(mean_A)

16.0


In [4]:
mean_b=np.mean(experiment_B)
print(experiment_B)

[10 13 15 16 19 21 18]


In [5]:
std_A=np.std(experiment_A)
print(std_A)

2.449489742783178


In [6]:
std_B=np.std(experiment_B)
print(std_B)

3.4641016151377544


In [7]:
max_A=np.max(experiment_A)
print(max_A)

20


In [8]:
max_B=np.max(experiment_B)
print(max_B)

21


In [9]:
min_A=np.min(experiment_A)
print(min_A)

12


In [10]:
min_B=np.min(experiment_B)
print(min_B)

10


In [11]:
diff=experiment_A-experiment_B
print(diff)

[ 2  2 -1  2  1 -4 -2]


In [12]:
if std_A >std_B:
    print("Experiment A shows greater variation\n")
elif std_B >std_A:
    print("Experiment B shows greater variation\n")
else:
    print("Both experiments show equal variation\n")


Experiment B shows greater variation

