In [1]:
import numpy as np

In [ ]:
import numpy as np


SUBJECTS = [
    "Mathematics",
    "Physics",
    "Programming",
    "Statistics"
]


def generate_marks(students=10, subjects=4):
    return np.random.randint(0, 101, size=(students, subjects))


def calculate_student_averages(marks):
    return np.mean(marks, axis=1)


def calculate_subject_averages(marks):
    return np.mean(marks, axis=0)


def assign_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 50:
        return "D"
    else:
        return "F"


def create_student_records(marks, averages):
    records = []

    for index, average in enumerate(averages):

        record = {
            "student_id": index + 1,
            "marks": marks[index].tolist(),
            "average": round(float(average), 2),
            "grade": assign_grade(average)
        }

        records.append(record)

    return records


def analyze_performance(marks):
    student_averages = calculate_student_averages(marks)
    subject_averages = calculate_subject_averages(marks)

    highest_student = np.argmax(student_averages) + 1
    lowest_student = np.argmin(student_averages) + 1

    highest_mark = np.max(marks)
    lowest_mark = np.min(marks)

    students_above_75 = np.count_nonzero(student_averages > 75)

    marks_above_90 = marks[marks > 90]

    return {
        "student_averages": student_averages,
        "subject_averages": subject_averages,
        "highest_student": highest_student,
        "lowest_student": lowest_student,
        "highest_mark": highest_mark,
        "lowest_mark": lowest_mark,
        "students_above_75": students_above_75,
        "marks_above_90": marks_above_90
    }


# Generate dataset
marks = generate_marks()

# Analyze dataset
analysis = analyze_performance(marks)

# Create final student records
student_records = create_student_records(
    marks,
    analysis["student_averages"]
)

print("=" * 60)
print("       STUDENT PERFORMANCE ANALYSIS")
print("=" * 60)

print("\nMarks Matrix:")
print(marks)


print("\nSubject-wise Marks")
print("-" * 60)

print(f"{'Student':<10}", end="")

for subject in SUBJECTS:
    print(f"{subject:<15}", end="")

print()

for i, row in enumerate(marks):
    print(f"Student {i + 1:<3}", end="")

    for mark in row:
        print(f"{mark:<15}", end="")

    print()


print("\nAverage Mark of Each Student:")
for i, average in enumerate(analysis["student_averages"]):
    print(f"Student {i + 1}: {average:.2f}")


print("\nAverage Mark of Each Subject:")
for subject, average in zip(
        SUBJECTS,
        analysis["subject_averages"]):

    print(f"{subject}: {average:.2f}")


print(
    "\nStudent with Highest Average: "
    f"Student {analysis['highest_student']}"
)

print(
    "Student with Lowest Average: "
    f"Student {analysis['lowest_student']}"
)


print("\nHighest Mark in Dataset:",
      analysis["highest_mark"])

print("Lowest Mark in Dataset:",
      analysis["lowest_mark"])


print(
    "\nNumber of Students with Average Above 75:",
    analysis["students_above_75"]
)


print("\nAll Marks Greater Than 90:")
print(analysis["marks_above_90"])


print("\nFinal Student Records")
print("-" * 60)

for student in student_records:

    print(
        f"Student {student['student_id']}: "
        f"Average = {student['average']:.2f}, "
        f"Grade = {student['grade']}"
    )

       STUDENT PERFORMANCE ANALYSIS

Marks Matrix:
[[81 76 82  5]
 [26 49  8 37]
 [54 72 67 73]
 [50 61 82 29]
 [66 14 85 78]
 [12 48 30  3]
 [99 66 61 78]
 [36 90 90 76]
 [25  6 74 62]
 [71 65 46 93]]

Subject-wise Marks
------------------------------------------------------------
Student   Mathematics    Physics        Programming    Statistics     
Student 1  81             76             82             5              
Student 2  26             49             8              37             
Student 3  54             72             67             73             
Student 4  50             61             82             29             
Student 5  66             14             85             78             
Student 6  12             48             30             3              
Student 7  99             66             61             78             
Student 8  36             90             90             76             
Student 9  25             6              74             62            