In [1]:
import numpy as np

In [2]:
image = np.array([
[0, 0, 0, 255, 255],
[0, 0, 128, 255, 255],
[0, 128, 128, 128, 255],
[0, 0, 128, 0, 0],
[255, 0, 0, 0, 255]
])

print(image)

[[  0   0   0 255 255]
 [  0   0 128 255 255]
 [  0 128 128 128 255]
 [  0   0 128   0   0]
 [255   0   0   0 255]]


In [3]:
minimum=np.min(image)
print(minimum)

0


In [4]:
maximum=np.max(image)
print(maximum)

255


In [5]:
mean=np.mean(image)
print(mean)

97.0


In [6]:
greater_than_100=image[image>100]
print(greater_than_100)

[255 255 128 255 255 128 128 128 255 128 255 255]


In [7]:
cnt_greater_than_100=np.count_nonzero(image>100)
print(cnt_greater_than_100)

12


In [8]:
pixels_255=image[image==255]
print(pixels_255)

[255 255 255 255 255 255 255]


In [9]:
high_intensity=image[image>100]