In [3]:
import numpy as np

In [8]:
measurment=np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])
print(measurment)

[ 10  12  15 200  13  11  14 250  12  15]


In [9]:
invalid=measurment[measurment>100]
print(invalid)

[200 250]


In [10]:
valid=measurment[measurment<=100]
print(valid)

[10 12 15 13 11 14 12 15]


In [11]:
mean_valid=np.mean(valid)
print(mean_valid)

12.75


In [12]:
minimum_valid=np.min(valid)
print(minimum_valid)

10


In [13]:
maximum_valid=np.max(valid)
print(maximum_valid)

15


In [14]:
print(measurment)

[ 10  12  15 200  13  11  14 250  12  15]
