In [ ]:
#1
import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)


[10 20 30 40 50]


In [ ]:
#2
import numpy as np
def temperature_analysis(temperatures):
    average = np.mean(temperatures)
    maximum = np.max(temperatures)
    minimum = np.min(temperatures)
    highest_day = np.argmax(temperatures) + 1
    above_average = temperatures[temperatures > average]
    print("Average temperature:", average)
    print("Maximum temperature:", maximum)
    print("Minimum temperature:", minimum)
    print("Day with highest temperature:", highest_day)
    print("Temperatures above average:", above_average)
temperatures = np.array([
    32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0
])
temperature_analysis(temperatures)

Average temperature: 31.842857142857145
Maximum temperature: 34.5
Minimum temperature: 29.8
Day with highest temperature: 5
Temperatures above average: [32.5 33.1 34.5]


In [ ]:
#3
import numpy as np
matrix=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(matrix)
print("\nfirst row:",matrix[0])
print("\nlast row:",matrix[-1])
print("\nfirst column:",matrix[:,0])
print("\nlast column:",matrix[:,-1])
print("\nmiddle 2*2 section:",matrix[0:2,1:3])
print("\nevery alternate element:",matrix[::2,::2])
print("\nshape:",matrix.shape)
print("\nnumber of dimensions:",matrix.ndim)
print("\ntotal number of elements:",matrix.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

first row: [1 2 3 4]

last row: [ 9 10 11 12]

first column: [1 5 9]

last column: [ 4  8 12]

middle 2*2 section: [[2 3]
 [6 7]]

every alternate element: [[ 1  3]
 [ 9 11]]

shape: (3, 4)

number of dimensions: 2

total number of elements: 12


In [ ]:
#4
import numpy as np
numbers=np.random.choice(
    np.arange(1,51),
    size=50,
    replace=False)
print(numbers)
even=numbers[numbers%2==0]
odd=numbers[numbers%2==1]
print("\neven numbers:",even)
print("\nodd numbers:",odd)

[45 30 11 31 25 16 50 44 14 47 33 38 24  1  5 40  2 29 17 19 28 12 48  3
 23  6 41 27 32 13 15 21 20  7 18 22 26 36  4 46 34 42 49  9 37  8 39 35
 43 10]

even numbers: [30 16 50 44 14 38 24 40  2 28 12 48  6 32 20 18 22 26 36  4 46 34 42  8
 10]

odd numbers: [45 11 31 25 47 33  1  5 29 17 19  3 23 41 27 13 15 21  7 49  9 37 39 35
 43]


In [ ]:
#5
import numpy as np
numbers=np.random.randint(1,101,30)
print(numbers)
above=numbers[numbers>50]
between=numbers[(numbers>=25)&(numbers<=75)]
count=len(above)
print("\nnumbers greater than 50:",above)
print("\nnumbers between 25 and 75:",between)
print("\ncount number greter than 50",count)
if count>0:
    average=np.mean(above)
    print("\nAverage of numbers greater than 50:",average)


[ 66  93  51  49   4  20   7  22  46  12  19  86  52  88  63  72  35 100
  96  48  13  31  10  19  92   8  30  33  94  53]

numbers greater than 50: [ 66  93  51  86  52  88  63  72 100  96  92  94  53]

numbers between 25 and 75: [66 51 49 46 52 63 72 35 48 31 30 33 53]

count number greter than 50 13

Average of numbers greater than 50: 77.38461538461539


In [ ]:
#6
import numpy as np
marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])
print("Student marks:",marks)
student_average = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)
highest_mark = np.max(marks)
lowest_mark = np.min(marks)
best_student = np.argmax(student_average)
subjects = [
    "Mathematics",
    "Physics",
    "Programming"
]
best_subject = np.argmax(subject_average)
print("\nAverage of each student:",student_average)
print("\nAverage of each subject:",subject_average)
print("\nHighest mark:",highest_mark)
print("\nLowest mark:",lowest_mark)
print("\nStudent with highest average:", best_student + 1)
print("\nSubject with highest average:",subjects[best_subject])

Student marks: [[78 82 91]
 [65 74 80]
 [92 88 95]
 [56 69 72]
 [84 90 87]]

Average of each student: [83.66666667 73.         91.66666667 65.66666667 87.        ]

Average of each subject: [75.  80.6 85. ]

Highest mark: 95

Lowest mark: 56

Student with highest average: 3

Subject with highest average: Programming


In [ ]:
#7
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])
print("\nMatrix A:",A)
print("\nMatrix B:",B)
print("\nAddition:",A+B)
print("\nSubstrction:",A-B)
print("\nElment wise multiplication:",A*B)
print("\nmatrix multiplication:",A@B)


Matrix A: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B: [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition: [[10 10 10]
 [10 10 10]
 [10 10 10]]

Substrction: [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Elment wise multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

matrix multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#8
import numpy as np
def transform_data(data):
    square = data ** 2
    square_root = np.sqrt(data)
    exponential = np.exp(data)
    print("Original data:",data)
    print("\nSquare:",square)
    print("\nSquare root:",square_root)
    print("\nExponential:",exponential)
    print("\nMean of square:",np.mean(square))
    print("\nMean of square root:",np.mean(square_root))
    print("\nMean of exponential:",np.mean(exponential))
data = np.array([2, 4, 6, 8, 10, 12])
transform_data(data)

Original data: [ 2  4  6  8 10 12]

Square: [  4  16  36  64 100 144]

Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]

Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]

Mean of square: 60.666666666666664

Mean of square root: 2.5530849508680995

Mean of exponential: 31371.271866746192


In [ ]:
#9
import numpy as np
numbers = np.arange(1, 25)
array_4x6 = numbers.reshape(4, 6)
array_6x4 = numbers.reshape(6, 4)
array_2x3x4 = numbers.reshape(2, 3, 4)
print("4 x 6 array:",array_4x6)
print("Shape:", array_4x6.shape)
print("\n6 x 4 array:",array_6x4)
print("Shape:", array_6x4.shape)
print("\n2 x 3 x 4 array:",array_2x3x4)
print("Shape:", array_2x3x4.shape)
one_dimension = array_4x6.flatten()
print("\nOne-dimensional array:",one_dimension)

4 x 6 array: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

6 x 4 array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)

2 x 3 x 4 array: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

One-dimensional array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
#10
import numpy as np
num1=np.array([10,20,30,40,50])
num2=np.array([15,25,35,45,55])
one_array=np.concatenate((num1,num2))
rows=np.vstack((num1,num2))
columns = np.column_stack((num1,num2))
print("\none dimensional array:",one_array)
print("shape:",one_array.shape)
print("\nExperiments as rows:",rows)
print("shape;",rows.shape)
print("\nExperiments as columns:",columns)
print("shape:",columns.shape)


one dimensional array: [10 20 30 40 50 15 25 35 45 55]
shape: (10,)

Experiments as rows: [[10 20 30 40 50]
 [15 25 35 45 55]]
shape; (2, 5)

Experiments as columns: [[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
shape: (5, 2)


In [ ]:
#11
import numpy as np
data=np.array([10,12,15,200,13,11,14,250,12,15])
invalid=data[data>100]
valid=data[data<=100]
print("original data:",data)
print("\nInvalid measurement:",invalid)
print("\nvalid measurement:",valid)
print("\nmean of valid measurement:",np.mean(valid))
print("\nminumum of valid measurement:",np.min(valid))
print("\nmaximum of valid measurement:",np.max(valid))

original data: [ 10  12  15 200  13  11  14 250  12  15]

Invalid measurement: [200 250]

valid measurement: [10 12 15 13 11 14 12 15]

mean of valid measurement: 12.75

minumum of valid measurement: 10

maximum of valid measurement: 15


In [ ]:
#12
import numpy as np
image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])
minimum = np.min(image)
maximum = np.max(image)
mean = np.mean(image)
above_100 = image[image > 100]
count = len(above_100)
pixels_255 = image[image == 255]
print("Minimum pixel intensity:",minimum)
print("\nMaximum pixel intensity:",maximum)
print("\nMean pixel intensity:",mean)
print("\nNumber of pixels greater than 100:",count)
print("\nPixels equal to 255:",pixels_255)
print("\nNew array containing pixels greater than 100:",above_100)

Minimum pixel intensity: 0

Maximum pixel intensity: 255

Mean pixel intensity: 97.0

Number of pixels greater than 100: 12

Pixels equal to 255: [255 255 255 255 255 255 255]

New array containing pixels greater than 100: [255 255 128 255 255 128 128 128 255 128 255 255]


In [ ]:
#13
import numpy as np
experiment_A = np.array([
    12, 15, 14, 18, 20, 17, 16
])
experiment_B = np.array([
    10, 13, 15, 16, 19, 21, 18
])
mean_A = np.mean(experiment_A)
std_A = np.std(experiment_A)
max_A = np.max(experiment_A)
min_A = np.min(experiment_A)

mean_B = np.mean(experiment_B)
std_B = np.std(experiment_B)
max_B = np.max(experiment_B)
min_B = np.min(experiment_B)
print("Experiment A")
print("Mean:", mean_A)
print("Standard deviation:", std_A)
print("Maximum:", max_A)
print("Minimum:", min_A)

print("\nExperiment B")
print("Mean:", mean_B)
print("Standard deviation:", std_B)
print("Maximum:", max_B)
print("Minimum:", min_B)

difference = experiment_A - experiment_B
print("\nDifference between experiments:",difference)

if std_A > std_B:
    print("\nExperiment A has greater variation.")
elif std_B > std_A:
    print("\nExperiment B has greater variation.")
else:
    print("\nBoth have the same variation.")

Experiment A
Mean: 16.0
Standard deviation: 2.449489742783178
Maximum: 20
Minimum: 12

Experiment B
Mean: 16.0
Standard deviation: 3.4641016151377544
Maximum: 21
Minimum: 10

Difference between experiments: [ 2  2 -1  2  1 -4 -2]

Experiment B has greater variation.


In [ ]:
#14
import numpy as np
def create_data():
    data = np.random.randint(1, 101,(10, 5))
    return data

def analyze_data(data):
    print("Dataset:",data)
    print("\nShape:",data.shape)
    print("\nNumber of dimensions:",data.ndim)
    variable_mean = np.mean(data,axis=0)
    print("\nMean of each variable:",variable_mean)
    experiment_mean = np.mean(data,axis=1)
    print("\nMean of each experiment:",experiment_mean)
    print("\nMaximum value:",np.max(data))
    print("\nMinimum value:",np.min(data))
    overall_mean = np.mean(data)
    print("\nOverall mean:",overall_mean)
    above_mean = data[data > overall_mean]
    print("\nValues above overall mean:",above_mean)
    reshaped = data.reshape(5, 10)
    print("\nReshaped data:",reshaped)
    print("New shape:",reshaped.shape)
    flattened = reshaped.flatten()
    print("\nFlattened data:",flattened)
data = create_data()
analyze_data(data)

Dataset: [[ 10  59  12  94  80]
 [ 84  49  86  72  12]
 [ 88  41  68  86  82]
 [ 10  38  95  57  20]
 [ 23  71  65  37  76]
 [ 88  82  68  76  78]
 [ 65 100  79  35  65]
 [ 44  84   5  86  89]
 [ 20  71  11  22  94]
 [  4  32  99   3  80]]

Shape: (10, 5)

Number of dimensions: 2

Mean of each variable: [43.6 62.7 58.8 56.8 67.6]

Mean of each experiment: [51.  60.6 73.  44.  54.4 78.4 68.8 61.6 43.6 43.6]

Maximum value: 100

Minimum value: 3

Overall mean: 57.9

Values above overall mean: [ 59  94  80  84  86  72  88  68  86  82  95  71  65  76  88  82  68  76
  78  65 100  79  65  84  86  89  71  94  99  80]

Reshaped data: [[ 10  59  12  94  80  84  49  86  72  12]
 [ 88  41  68  86  82  10  38  95  57  20]
 [ 23  71  65  37  76  88  82  68  76  78]
 [ 65 100  79  35  65  44  84   5  86  89]
 [ 20  71  11  22  94   4  32  99   3  80]]
New shape: (5, 10)

Flattened data: [ 10  59  12  94  80  84  49  86  72  12  88  41  68  86  82  10  38  95
  57  20  23  71  65  37  76  88  82  68

In [ ]:
#15
import numpy as np
def create_data():
  data = np.random.randint(1,101,(10, 5))
  return data
def analyze_data(data):
  print("Dataset:",data)
  print("\nShape:",data.shape)
  print("\nNumber of dimensions:",data.ndim)
variable_mean = np.mean(data,axis=0)
print("\nMean of each variable:",variable_mean)
experiment_mean = np.mean(data,axis=1)
print("\nMean of each experiment:",experiment_mean)
print("\nMaximum value:",np.max(data))
print("\nMinimum value:",np.min(data))
overall_mean = np.mean(data)
print("\nOverall mean:",overall_mean)
above_mean = data[data > overall_mean]
print("\nValues above overall mean:",above_mean)
reshaped = data.reshape(5, 10)
print("\nReshaped data:",reshaped)
print("New shape:",reshaped.shape)
flattened = reshaped.flatten()
print("\nFlattened data:",flattened)
data = create_data()
analyze_data(data)


Mean of each variable: [50.4 58.8 54.2 61.4 53.2]

Mean of each experiment: [70.2 80.6 34.  37.2 60.4 61.4 57.8 61.4 31.6 61.4]

Maximum value: 98

Minimum value: 1

Overall mean: 55.6

Values above overall mean: [98 80 83 71 90 90 95 96 78 64 65 80 92 93 81 67 79 64 93 88 69 79 80 79
 73 85]

Reshaped data: [[98 80 19 83 71 90 32 90 95 96]
 [12 18  8 78 54 20 64 49 51  2]
 [43 65 80 92 22 12 93 81 67 54]
 [79 64 17 36 93 88 69 45 26 79]
 [27 24 80  1 26 35 79 73 85 35]]
New shape: (5, 10)

Flattened data: [98 80 19 83 71 90 32 90 95 96 12 18  8 78 54 20 64 49 51  2 43 65 80 92
 22 12 93 81 67 54 79 64 17 36 93 88 69 45 26 79 27 24 80  1 26 35 79 73
 85 35]
Dataset: [[27 94 73 79 49]
 [59 49 70 13 39]
 [64 88 36 30 81]
 [82 42 19 46 86]
 [43 16 14 74 18]
 [29 56 67 66 40]
 [35 74 28 36 17]
 [75 14 62 56 24]
 [ 7 86 74 43 63]
 [93 20 58 86 36]]

Shape: (10, 5)

Number of dimensions: 2
