In [ ]:
l1=[1,2,3,6,7,8]
l2=[2,4,5,7,8,9]
print(l1,l2)


[1, 2, 3, 6, 7, 8] [2, 4, 5, 7, 8, 9]


In [5]:
prod=[]
for i in range(len(l1)):
    print(l1[i]*l2[i])
    prod.append(l1[i]*l2[i])
    print(prod)


2
[2]
8
[2, 8]
15
[2, 8, 15]
42
[2, 8, 15, 42]
56
[2, 8, 15, 42, 56]
72
[2, 8, 15, 42, 56, 72]


In [ ]:

import numpy 
a=numpy.array(l1)
b=numpy.array(l2)
print(a,b)
print(a*b)
#print(a+b)
#print(a-b)


[1 2 3 6 7 8] [2 4 5 7 8 9]
[ 2  8 15 42 56 72]


In [12]:
import numpy as np
a=np.array([1,2,4 ,7 ,8,9])
print("Array:",a)
print("Shape of array:",a.shape)
print("Dimension of array:",a.ndim)
print("Size of array:",a.size)
print("Data type of array:",a.dtype)
print("type:",type(a))

Array: [1 2 4 7 8 9]
Shape of array: (6,)
Dimension of array: 1
Size of array: 6
Data type of array: int64
type: <class 'numpy.ndarray'>


In [23]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.arange(1,6)
arr3=np.zeros(5)
arr4=np.ones(5)
arr5=np.linspace(1,10,5)
arr6=np.empty(6)

In [ ]:
matrix=np.array([[1,2,3,],[4,5,6]])
matrix
print("Matrix:",matrix)
print("Shape of matrix:",matrix.shape)



Matrix: [[1 2 3]
 [4 5 6]]
Shape of matrix: (2, 3)


In [6]:
arr=np.array([1,2,3,4,6])
print("Sum of arr:",np.sum(arr))

Sum of arr: 16


In [15]:


arr1 = np.array([1,3,6,7,8,9,0,9,8])
arr1 = arr1.reshape(3,3)
print("Reshaped array:", arr1)

Reshaped array: [[1 3 6]
 [7 8 9]
 [0 9 8]]


In [20]:
arr = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(arr)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("inverse of arr:\n", np.linalg.inv(arr))

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
inverse of arr:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
import numpy as np
arr=np.arange(12)
print(f"original array:\n{arr}")
matrix=arr.reshape(3,4)
f=matrix.flatten()
r=matrix.ravel()
#print(f"flattened array:\n{matrix.flatten()}")
#print(f"Raveled array:\n{matrix.ravel()}")
f[0]=100
print(f"flattened array:\n{f}")
print(f"flattened array:\n{matrix}")
f[0]=200
print(f"Raveled array:\n{r}")
print(f"Raveled array:\n{matrix}")

original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
flattened array:
[100   1   2   3   4   5   6   7   8   9  10  11]
flattened array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Raveled array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
a=np.array([[1,2,3],[5,8,9]])
b=np.array([[4,5,6],[1,2,4]])
print(a)
print(b)
print(f"concatenation:")
print(f"Horizantal:\n",np.concatenate([a,b]))
print(f"Horizantal(hstack):\n",np.hstack([a,b]))

[[1 2 3]
 [5 8 9]]
[[4 5 6]
 [1 2 4]]
concatenation:
Horizantal:
 [[1 2 3]
 [5 8 9]
 [4 5 6]
 [1 2 4]]
Horizantal(hstack):
 [[1 2 3 4 5 6]
 [5 8 9 1 2 4]]


In [ ]:
#pandas
students=[
    ["A"]
]