In [5]:
l1=[1,2,3,4,5]
l2=[5,6,7,8,9]
prod=[]
for i in range(len(l1)):
    print(l1[i]*l2[i])
    prod.append(l1[i]*l2[i])
print(prod)




5
12
21
32
45
[5, 12, 21, 32, 45]


In [ ]:
#numpy=numerical python

import numpy
a=numpy.array(l1)
b=numpy.array(l2)
print(a,b)
print(a*b)

[1 2 3 4 5] [5 6 7 8 9]
[ 5 12 21 32 45]


In [8]:
import numpy as np
#craete numpy array

a=np.array([1,2,3,4,5])
print("Array:",a)
print("Type:",type(a))
print("Data Type:",a.dtype)
print("Shape:",a.shape)
print("Size:",a.size)
print("Dimension:",a.ndim)   
print()

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data Type: int64
Shape: (5,)
Size: 5
Dimension: 1



In [10]:
arr1=np.array([1,2,3,4,5])
arr2=np.arange(1,6)
arr3=np.zeros(5)
arr4=np.ones(5)
arr5=np.linspace(0,10,5)
arr6=np.empty(6)

print("From List",arr1)
print("Range:",arr2)
print("Zeros:",arr3)
print("Ones:",arr4)
print("Linspace:",arr5)
print("Empty:",arr6)

From List [1 2 3 4 5]
Range: [1 2 3 4 5]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Linspace: [ 0.   2.5  5.   7.5 10. ]
Empty: [6.23042070e-307 4.67296746e-307 1.69121096e-306 6.23058707e-307
 2.22526399e-307 2.05837348e-312]


In [ ]:
#2D Array



In [14]:
matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix:",matrix)
print("Shape:",matrix.shape)
print("Sum::",np.sum(matrix))

Matrix: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Sum:: 21


In [19]:
ar=np.array([1,2,3,4,5,6,7,8,9])
ans=ar.reshape(3,3)
print(ans)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
arr10=np.array([[1,2],[4,4]])
print("inverse:",np.linalg.inv(arr10))


inverse: [[-1.    0.5 ]
 [ 1.   -0.25]]


In [27]:
arr=np.array(12)
print(f"Original Array::{arr}")
print(f"Reshape to (3,4):\n{arr.reshape(3,4)}")
matrix=arr.reshape(3,4)
print(f"Flattend:{matrix.flatten()}")

Original Array::12


ValueError: cannot reshape array of size 1 into shape (3,4)

In [33]:

a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[6,7,8],[9,1,2]])
print(f"Concatinate::\n{np.concatenate([a1,a2]).shape}")
print(f"Horizontal\n { np.hstack([a1,a2]).shape}")

Concatinate::
(4, 3)
Horizontal
 (2, 6)
