In [3]:
import numpy as np

In [4]:
data = np.arange(1, 25)


In [5]:
array_4x6 = data.reshape(4, 6)
print(array_4x6)
print(array_4x6.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)


In [6]:
array_6x4 = data.reshape(6, 4)
print(array_6x4)
print(array_6x4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)


In [7]:
array_2x3x4 = data.reshape(2, 3, 4)
print(array_2x3x4)
print(array_2x3x4.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [8]:
flattened = array_4x6.flatten()
print(flattened)
print(flattened.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)
