In [1]:
import numpy as np

In [6]:
students=np.array([[78,82,91],[65,74,80],[92,88,95],[56,69,72],[84,97,87]])
student_avg=np.mean(students,axis=1)
print(student_avg)

[83.66666667 73.         91.66666667 65.66666667 89.33333333]


In [8]:
sub_avg=np.mean(students,axis=0)
print(sub_avg)

[75. 82. 85.]


In [10]:
highest_mark = np.max(students)
print(highest_mark)

97


In [11]:
lowest_mark = np.min(students)
print(lowest_mark)

56


In [12]:
highest_student = np.argmax(student_avg) + 1
print(highest_student)

3


In [15]:
subjects = ["Mathematics", "Physics", "Programming"]
highest_subject = students[np.argmax(sub_avg)]
print(highest_subject)

[92 88 95]
