In [4]:
import numpy as np

In [5]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
print(arr[0,:])

[1 2 3 4]


In [8]:
print(arr[-1,:])

[ 9 10 11 12]


In [9]:
print(arr[:,0])

[1 5 9]


In [10]:
print(arr[:,-1])

[ 4  8 12]


In [11]:
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [14]:
print(arr.flat[::2])

[ 1  3  5  7  9 11]


In [15]:
print(arr.shape)

(3, 4)


In [17]:
print(arr.ndim)

2


In [19]:
print(arr.size)

12
