In [9]:
import numpy as np

In [10]:
experiment_1 = [10, 20, 30, 40, 50]
experiment_2 = [15, 25, 35, 45, 55]

In [11]:
combine_1D=np.concatenate((experiment_1,experiment_2))
print(combine_1D)
print(combine_1D.shape)

[10 20 30 40 50 15 25 35 45 55]
(10,)


In [12]:
combine_row=np.vstack((experiment_1,experiment_2))
print(combine_row)
print(combine_row.shape)

[[10 20 30 40 50]
 [15 25 35 45 55]]
(2, 5)


In [13]:
combine_col=np.column_stack((experiment_1,experiment_2))
print(combine_col)
print(combine_col.shape)

[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
(5, 2)
