In [1]:
import numpy as np


def transform_data(data):
    squares = np.square(data)
    square_roots = np.sqrt(data)
    exponentials = np.exp(data)

    means = {
        "square_mean": np.mean(squares),
        "sqrt_mean": np.mean(square_roots),
        "exponential_mean": np.mean(exponentials)
    }

    return squares, square_roots, exponentials, means


data = np.array([2, 4, 6, 8, 10, 12])

squares, roots, exponentials, means = transform_data(data)

print("Original Data:")
print(data)

print("\nSquares:")
print(squares)

print("\nSquare Roots:")
print(roots)

print("\nExponentials:")
print(exponentials)

print("\nMean of Squares:", means["square_mean"])
print("Mean of Square Roots:", means["sqrt_mean"])
print("Mean of Exponentials:", means["exponential_mean"])

Original Data:
[ 2  4  6  8 10 12]

Squares:
[  4  16  36  64 100 144]

Square Roots:
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]

Exponentials:
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]

Mean of Squares: 60.666666666666664
Mean of Square Roots: 2.5530849508680995
Mean of Exponentials: 31371.271866746192
