In [9]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [10]:
addition = A + B
print(addition)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
subtraction = A - B
print(subtraction)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [12]:
multiplication=A*B
print(multiplication)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [13]:
matrix_multiplication = A @ B
print(matrix_multiplication)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
